### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by batden**

### CODE REVIEW

**Comment by thewaiter** [comment]
You are great as usual :) THX a lot

**Comment by thewaiter** [comment]
Wait, do not we need a desktop file name in french "séparateur"

**Comment by batden** [comment]
No, it's not needed. French people will understand quite well what "separator" means because it's almost the same word in my language. And I tend to avoid using accents (diacritical marks as in "S**é**parateur") in apps and modules names.
Don't worry.

**Comment by thewaiter** [comment]
OK then, I got you

**Comment by thewaiter** [comment]
BTW, are you available on discord? I would like to ask you something...

**Pull request merged**
